Repository cloud-native-toolkit/automation-solutions, pull requests merged in 2022-06, with the labels that each got.

#131 Fixes logic for colima update
  common-files/launch.sh
Labels: bug

#134 Pins cli-tools version to v1.1-v1.8.1
  common-files/launch.sh
Labels: chore

#162 Updated AWS Quickstart BOMs
  boms/infrastructure/aws/_common/gitops/200-aws-openshift-gitops.yaml
  boms/infrastructure/aws/_common/gitops/220-dev-tools.yaml
  boms/infrastructure/aws/openshift/1-quickstart/105-aws-vpc-openshift.yaml
Labels: bug, minor

#167 Data Fabric BOMs with ODF and Portworx
  boms/software/datafabric/600-datafabric-services-odf.yaml
  boms/software/datafabric/600-datafabric-services-portworx.yaml
  boms/software/datafabric/600-datafabric-services.yaml
  boms/software/datafabric/610-datafabric-demo.yaml
Labels: draft
